Homework #7
artemius39/java-course-2023 pull request #10
Opened 2023-11-25 19:13 UTC by artemius39

2023-11-27 13:20 UTC, nexen505 requested changes

2023-11-27 13:20 UTC, nexen505 commented on src/test/java/edu/hw7/task1/AtomicCounterTest.java
> +        Thread[] threads = new Thread[10];
Проблема: такой подход приводит к необходимости ручного управления потоками.

Предложение: изменить реализацию на использование `Executors#newFixedThreadPool`.

2023-11-27 13:20 UTC, nexen505 commented on src/main/java/edu/hw7/task3/BaseDataBase.java
> +        idMap.put(person.id(), person);
Предложение: учесть коллизию, где по тому же идентификатору положили другого `Person`.

2023-11-27 13:20 UTC, nexen505 commented on src/main/java/edu/hw7/task3/BaseDataBase.java
> +        return List.copyOf(nameMap.get(name));
Проблема: тут и далее будет `NullPointerException` в случае, если не найдено по имени.

Предложение: корректно избежать этого тут и в соседних методах.

2023-11-27 13:20 UTC, nexen505 commented on src/main/java/edu/hw7/task4/MultiThreadedComputer.java
> +        for (int thread = 0; thread < threadCount; thread++) {
Проблема: такой подход приводит к необходимости ручного управления потоками. Кроме того, в текущем коде создаваемые потоки не прерываются, если вдруг прервали ожидание `latch`.

Предложение: тут и в тестах изменить реализацию на использование `Executors#newFixedThreadPool`.

2023-11-27 14:08 UTC, artemius39 commented on src/test/java/edu/hw7/task1/AtomicCounterTest.java
> +        Thread[] threads = new Thread[10];
Исправил

2023-11-27 14:10 UTC, artemius39 commented on src/main/java/edu/hw7/task3/BaseDataBase.java
> +        idMap.put(person.id(), person);
Теперь вместо `put` делаю `putIfAbsent` и если в мапе что-то уже лежало, то бросаю исключение

2023-11-27 14:13 UTC, artemius39 commented on src/main/java/edu/hw7/task3/BaseDataBase.java
> +        return List.copyOf(nameMap.get(name));
Нет. В [документации к ListMultimap#get](https://guava.dev/releases/23.0/api/docs/com/google/common/collect/ListMultimap.html#get-K-) явно указано, что если ничего не найдено, то будет возвращён пустой список:

> Note that when `containsKey(key)` is false, this returns an empty collection, not `null`

2023-11-27 14:14 UTC, artemius39 commented on src/main/java/edu/hw7/task4/MultiThreadedComputer.java
> +        for (int thread = 0; thread < threadCount; thread++) {
Исправил

2023-11-28 13:58 UTC, nexen505 approved these changes

2023-11-29 19:10 UTC, merged