Homework #8
artemius39/java-course-2023 pull request #11
Opened 2023-12-02 12:27 UTC by artemius39

2023-12-03 15:09 UTC, artemius39 commented
## Перебор паролей

### Характеристики моего компьютера

- Модель: Ноутбук MacBookAir 6,2

- Процессор: Intel Core i7

- Тактовая частота: 1.7 GHz

- Количество ядер: 2

- Hyper-Threading: Включён

### Результаты измерения скорости

_При замерах я перебирал пароли длины от 0 до 4_

|  Количество потоков  | Скорость выполнения, мс | Прирост скорости, раз |
|:--------------------:|:-----------------------:|:---------------------:|
| Однопоточное решение |          3720           |           1           |
|          1           |          3561           |         1.04          |
|          2           |          2071           |          1.8          |
|          3           |          1973           |         1.89          |
|          4           |          2034           |         1.83          |
|          5           |          1982           |         1.88          |
|          6           |          2044           |         1.82          |
|          7           |          2024           |         1.84          |
|          8           |          2032           |         1.83          |
|          16          |          2000           |         1.86          |
|          32          |          1965           |         1.89          |
|         100          |          1935           |         1.92          |
|         1000         |          2093           |         1.78          |

2023-12-04 13:12 UTC, nexen505 requested changes

2023-12-04 13:12 UTC, nexen505 commented on src/main/java/edu/hw8/task1/QuoteServer.java
> +            while (running) {
Мысль: вместо `running` можно использовать `selector.isOpen()` + создавать селектор при вызове `start`.

2023-12-04 13:12 UTC, nexen505 commented on src/main/java/edu/hw8/task1/QuoteServer.java
> +                selector.select(TIMEOUT);
Косметика: можно проверить возвращаемое значение и продолжить цикл, если там "пусто".

2023-12-04 13:12 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            tasks.put(runnable);
Проблема: возможна блокировка потока.

Предложение: использовать `java.util.concurrent.BlockingQueue#offer(E, long, java.util.concurrent.TimeUnit)` и выбросить `java.util.concurrent.RejectedExecutionException` в случае неудачного добавления задачи.

2023-12-04 13:12 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                thread.join();
Проблема: возможна блокировка потока.

Предложение: использовать `java.lang.Thread#join(java.time.Duration)` и прервать поток вручную в случае неудачи в ожидании.

2023-12-04 13:12 UTC, nexen505 commented on src/main/java/edu/hw8/task3/PasswordGenerator.java
> +public interface PasswordGenerator {
Косметика: можно реализовать интерфейс `java.util.Iterator<String>` для идиоматичности.

2023-12-04 14:33 UTC, artemius39 commented on src/main/java/edu/hw8/task1/QuoteServer.java
> +            while (running) {
Вынес селектор в поле, в цикле проверяю на `isOpen`, а в `shutdown` его закрываю. `running` убрал

2023-12-04 14:34 UTC, artemius39 commented on src/main/java/edu/hw8/task1/QuoteServer.java
> +                selector.select(TIMEOUT);
Если возвращается 0, то делаю `continue`

2023-12-04 14:35 UTC, artemius39 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            tasks.put(runnable);
Исправил. Хотя мне не совсем понятно, в каком случае будет блокировка, если я использовал `LinkedBlockingQueue` с неограниченным размером.

2023-12-04 14:36 UTC, artemius39 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                thread.join();
Добавил таймаут

2023-12-04 14:38 UTC, artemius39 commented on src/main/java/edu/hw8/task3/PasswordGenerator.java
> +public interface PasswordGenerator {
Сделал `extends Iterator<String>`, методы `hasNextPassword` и `nextPassword` убрал, вместо них использую `hasNext` и `next` от `Iterator`.

2023-12-05 13:48 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            tasks.put(runnable);
Так с точки зрения реализации более гибко получается: возможное ограничение размера очереди ее не сломает.

2023-12-05 13:49 UTC, nexen505 approved these changes

2023-12-05 16:16 UTC, merged