Homework #9
artemius39/java-course-2023 pull request #12
Opened 2023-12-05 19:35 UTC by artemius39

2023-12-08 10:50 UTC, nexen505 requested changes

2023-12-08 10:50 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +                    while (!executorService.isShutdown() || !tasks.isEmpty()) {
Мысль: вместо проверки остановки пула в таком случае лучше пользоваться статусом прерванности самого потока, чтобы на завязываться на пул за ненадобностью.

2023-12-08 16:42 UTC, artemius39 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +                    while (!executorService.isShutdown() || !tasks.isEmpty()) {
Добавил флаг `interrupted`, проверяю его значение. В `stats` делаю `shutdownNow`, чтобы прервать потоки.

2023-12-12 11:59 UTC, nexen505 approved these changes

2023-12-13 11:49 UTC, merged