Project #1
artemius39/java-course-2023 pull request #3
Opened 2023-10-15 09:42 UTC by artemius39

2023-10-23 14:29 UTC, nexen505 requested changes

2023-10-23 14:29 UTC, nexen505 commented on src/main/java/edu/project1/HangmanSession.java
> +    public GuessResult tryGuess(char guess) {
Проблема: при вводе одной и той же буквы несколько раз игрок проигрывает, что не user-friendly. Лучше выводить сообщение мол "вы уже это вводили - попробуйте другую букву".

Предложение: проработать этот сценарий.

2023-10-23 15:03 UTC, artemius39 commented on src/main/java/edu/project1/HangmanSession.java
> +    public GuessResult tryGuess(char guess) {
Добавил проверку в `ConsoleUserInterface`

2023-10-27 11:15 UTC, nexen505 approved these changes

2023-10-28 12:11 UTC, merged