Homework #3
artemius39/java-course-2023 pull request #4
Opened 2023-10-22 13:12 UTC by artemius39

2023-10-30 13:01 UTC, nexen505 requested changes

2023-10-30 13:01 UTC, nexen505 commented on src/main/java/edu/hw3/task2/Task2.java
> +        StringBuilder currentCluster = new StringBuilder();
Косметика: тут стоит указать у `StringBuilder` максимально возможный размер, чтобы оптимизировать работу с памятью.

2023-10-30 13:01 UTC, nexen505 commented on src/main/java/edu/hw3/task2/Task2.java
> +            currentCluster.append(parentheses.charAt(i));
Косметика: полученный символ можно в переменную вытащить для дальнейшего переиспользования.

2023-10-30 13:01 UTC, nexen505 commented on src/main/java/edu/hw3/task3/Task3.java
> +            freqDict.put(element, freqDict.getOrDefault(element, 0) + 1);
Проблема: конструкция неатомарна и сложна для восприятия.

Предложение: использовать метод `java.util.Map#merge`

2023-10-30 13:01 UTC, nexen505 commented on src/main/java/edu/hw3/task5/Task5.java
> +        if (name[0].isEmpty()) {
Косметика: `name[0]` можно в переменную вытащить для переиспользования.

2023-10-30 13:01 UTC, nexen505 commented on src/main/java/edu/hw3/task6/HeapMarket.java
> +    private static final Comparator<Stock> COMPARE_BY_VALUE_DESCENDING = Comparator.comparing(Stock::value).reversed();
Косметика: с учетом известного типа `Stock::value` можно воспользоваться `Comparator#comparingInt` для сужения логики сравнения.

2023-10-30 13:01 UTC, nexen505 commented on src/test/java/edu/hw3/task6/Task6Test.java
> +        Stock tinkoff = new Stock(Integer.MAX_VALUE, "tinkoff");
:)

2023-10-30 13:01 UTC, nexen505 commented on src/test/java/edu/hw3/task7/Task7Test.java
> +class Task7Test {
Косметика: для идиоматичности тестов можно воспользоваться проверками из `org.assertj.core.api.AbstractMapAssert`

2023-10-30 13:01 UTC, nexen505 commented on src/test/java/edu/hw3/task8/BackwardIteratorTest.java
> +class BackwardIteratorTest {
Косметика: тесты можно сделать идиоматичнее, если:
1) в тестах через лямбды создать `Iterable` на основе `Iterator`,
2) воспользоваться проверками на точный состав `Iterable` из `org.assertj.core.api.AbstractIterableAssert`

2023-10-30 18:17 UTC, artemius39 commented on src/main/java/edu/hw3/task2/Task2.java
> +        StringBuilder currentCluster = new StringBuilder();
Сделал `capacity` равную размеру строки. 

Хотя на мой вгляд, это не всегда оптимально: с начальной `capacity` по умолчанию будет сделано аллокаций на примерно `2 * m` символов, где `m` &mdash; размер наибольшего кластера в строке. Если в строке нет больших кластеров, например `()()()()()()()`, то без задания максимальной `capacity` памяти будет использовано меньше.

2023-10-30 18:18 UTC, artemius39 commented on src/main/java/edu/hw3/task2/Task2.java
> +            currentCluster.append(parentheses.charAt(i));
fixed

2023-10-30 18:18 UTC, artemius39 commented on src/main/java/edu/hw3/task3/Task3.java
> +            freqDict.put(element, freqDict.getOrDefault(element, 0) + 1);
Переписал через `merge`

2023-10-30 18:19 UTC, artemius39 commented on src/main/java/edu/hw3/task5/Task5.java
> +        if (name[0].isEmpty()) {
Вынес в переменную

2023-10-30 18:19 UTC, artemius39 commented on src/main/java/edu/hw3/task6/HeapMarket.java
> +    private static final Comparator<Stock> COMPARE_BY_VALUE_DESCENDING = Comparator.comparing(Stock::value).reversed();
fixed

2023-10-30 18:19 UTC, artemius39 commented on src/test/java/edu/hw3/task7/Task7Test.java
> +class Task7Test {
fixed

2023-10-30 18:20 UTC, artemius39 commented on src/test/java/edu/hw3/task8/BackwardIteratorTest.java
> +class BackwardIteratorTest {
Теперь создаю `Iterable` через `() -> new BackwardIterator<>(collection)` и его проверяю через `contains`.

2023-11-02 13:33 UTC, nexen505 commented on src/main/java/edu/hw3/task2/Task2.java
> +        StringBuilder currentCluster = new StringBuilder();
Изменение размера, кроме аллокации, включает в себя копирование старого содержимого - задание размера в среднем достаточно экономит сложность наполнения.

2023-11-02 13:34 UTC, nexen505 approved these changes

2023-11-04 11:21 UTC, merged