Project #2
artemius39/java-course-2023 pull request #5
Opened 2023-11-01 12:03 UTC by artemius39

2023-11-09 13:44 UTC, nexen505 requested changes
Крутая работа. Подкинул лишь некоторые вопросы.

2023-11-09 13:44 UTC, nexen505 commented on src/main/java/edu/project2/Generator.java
> +public interface Generator {
Косметика: интерфейс лишний в силу наличия `MazeGenerator` - можно удалить.

2023-11-09 13:44 UTC, nexen505 commented on src/main/java/edu/project2/GraphTraversingGenerator.java
> +                new Coordinate(0, randomEvenNumber(cols)),
Вопрос: почему выбирается четное число в качестве правой координаты?

2023-11-09 13:44 UTC, nexen505 commented on src/main/java/edu/project2/KruskalGenerator.java
> +public class KruskalGenerator extends GraphTraversingGenerator {
Вопрос: почему по алгоритму получается, что при четном размере с его стороны генерируется дополнительная стена? Можно ли это исправить?

2023-11-09 13:57 UTC, artemius39 commented on src/main/java/edu/project2/GraphTraversingGenerator.java
> +                new Coordinate(0, randomEvenNumber(cols)),
Потому что тогда там гарантированно будет проход. Генераторы работают так, что клетки с чётными координатами -- это вершины графа, в них всегда проход, а клетки между ними -- рёбра, их тип определяется в ходе генерации и может оказаться, что там стена.

2023-11-10 17:15 UTC, artemius39 commented on src/main/java/edu/project2/Generator.java
> +public interface Generator {
Убрал

2023-11-10 17:23 UTC, artemius39 commented on src/main/java/edu/project2/KruskalGenerator.java
> +public class KruskalGenerator extends GraphTraversingGenerator {
Потому что в клетках с нечётной строкой или столбцом проход генерируется только если она находится между двумя клетками с чётными координатами. То есть, например, если в лабиринте 10 строк, то клетка на 9-й строке может быть проходом, если клетки справа и слева имеют чётные координаты, что невозможно, так как строка у них нечётная, или сверху или снизу -- это тоже невозможно, потому что клетки снизу вовсе не существует.

Исправить это можно если дополнительно пройтись по нижнему ряду и правому столбцу и случайно расставить там проходы.

2023-11-13 13:27 UTC, nexen505 approved these changes

2023-11-13 13:56 UTC, merged