Homework #4
artemius39/java-course-2023 pull request #6
Opened 2023-11-05 19:15 UTC by artemius39

2023-11-08 13:49 UTC, nexen505 requested changes

2023-11-08 13:49 UTC, nexen505 commented on src/main/java/edu/hw4/Animals.java
> +        for (Animal animal : animals) {
Проблема: реализация не использует Stream API.

Предложение: привести реализацию в соответствие с заданием.

2023-11-09 13:43 UTC, artemius39 commented on src/main/java/edu/hw4/Animals.java
> +        for (Animal animal : animals) {
Сделал через Stream API

2023-11-10 05:16 UTC, nexen505 requested changes

2023-11-10 05:16 UTC, nexen505 commented on src/main/java/edu/hw4/Animals.java
> +                .collect(Collectors.toMap(
Проблема: `collect` делается дважды, что неоптимально.

Предложение: преобразовать поток в поток из `Map.Entry<String, Set<ValidationError>>` и собрать его в нужную структуру единожды.

2023-11-10 17:12 UTC, artemius39 commented on src/main/java/edu/hw4/Animals.java
> +                .collect(Collectors.toMap(
fixed

2023-11-13 11:33 UTC, nexen505 approved these changes

2023-11-13 13:55 UTC, merged