Homework #6
artemius39/java-course-2023 pull request #8
Opened 2023-11-15 20:57 UTC by artemius39

2023-11-17 09:21 UTC, nexen505 requested changes

2023-11-17 09:21 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            // TODO
Вопрос: здесь нужна доработка?

2023-11-17 09:21 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +public class DiskMap implements Map<String, String> {
Проблема: текущая реализация создает файл на каждую пару, хотя в задании говорится создать один файл с хранением списка пар.

Предложение: исправить реализацию.

2023-11-17 09:21 UTC, nexen505 commented on src/test/java/edu/hw6/task1/DiskMapTest.java
> +class DiskMapTest {
Предложение: добавить тесты на структуру дискового содержимого при операциях.

2023-11-20 17:16 UTC, artemius39 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            // TODO
Нет. IDE не нравилось, что я `Files.walk` вызываю без `try-with-resources`, но на самом деле при `skip` никакого исключения быть не может, а после `skip` этот поток уже используется внутри `try-with-resources` блока, так что никакой утечки ресурсов быть не может. Я оставил комментарий, чтобы потом ещё раз подумать над этим. В итоге я решил, что всё же здесь всё в порядке.

2023-11-20 17:18 UTC, artemius39 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +public class DiskMap implements Map<String, String> {
В чате в телеграме Александр Бирюков говорил, что так тоже можно:
https://t.me/c/1690654462/8742
https://t.me/c/1690654462/8744
https://t.me/c/1690654462/8745

2023-11-20 18:23 UTC, artemius39 commented on src/test/java/edu/hw6/task1/DiskMapTest.java
> +class DiskMapTest {
Добавил тесты на то, что при `put` файл создаётся, а при `remove` -- удаляется

2023-11-23 12:55 UTC, nexen505 commented on src/test/java/edu/hw6/task1/DiskMapTest.java
> +        Path tmp = Path.of("tmp");
Предложение: воспользоваться тут и в схожих тестах https://junit.org/junit5/docs/5.4.0/api/org/junit/jupiter/api/io/TempDir.html для создания временной директории. Такой механизм уже содержит в себе очистку файлов по окончании теста.

2023-11-23 15:36 UTC, artemius39 commented on src/test/java/edu/hw6/task1/DiskMapTest.java
> +        Path tmp = Path.of("tmp");
Сделал через `@TempDir`

2023-11-24 12:39 UTC, nexen505 approved these changes

2023-11-24 13:43 UTC, merged