Project #3
artemius39/java-course-2023 pull request #9
Opened 2023-11-19 15:04 UTC by artemius39

2023-11-22 12:11 UTC, nexen505 requested changes

2023-11-22 12:11 UTC, nexen505 commented on src/main/java/edu/project3/URLLogReader.java
> +    private final HttpClient client;
Проблема: ресурс не закрывается.

Предложение: сделать `LogReader implements AutoCloseable` и закрывать ресурс.

2023-11-22 16:23 UTC, artemius39 commented on src/main/java/edu/project3/URLLogReader.java
> +    private final HttpClient client;
Исправил

2023-11-24 13:24 UTC, nexen505 approved these changes

2023-11-24 13:40 UTC, merged